platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!
#inhibit_all_warnings!

use_modular_headers!

target 'ToolCollection_Example' do
  pod 'ToolCollection', :path => '../'

end
